config/routes.rb
Rails.application.routes.draw do
  default_url_options host: "localhost:3000"
 #devise_for :admin_users, {class_name: 'User' }.merge(ActiveAdmin::Devise.config)
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registrations: "registrations" }

  get ":student_no/:block", to: "students#index", param: :block, via: [:get], as: :block

  resources :students, path: '/:block', except: :index do
    collection do
      resources :subject_assignments do
        resources :announcements
        resources :exam_schedules
        resources :subject_grades
      end

    end
  end

  resources :teachers


  get "/teaching_loads", to: "teachers#index" do
  end
  
  devise_scope :user do
    root 'devise/sessions#new'
  end
  
end

app/models/student.rb
class Student < ApplicationRecord
  after_create :generate_student_no
  belongs_to :user, optional: true

  has_one  :block_assignment, dependent: :nullify
  has_many :blocks, through: :block_assignment, dependent: :nullify

  has_many   :subjects, through: :blocks

  has_many   :subject_grades, dependent: :destroy

  def student_name 
    "#{self.user.first_name} #{self.user.last_name}"
  end

  
  def generate_student_no
    current_known_batch = Student.all.group_by { |y| y.created_at.year }
    order_of_enrollment = current_known_batch[Date.today.year].find_index(self)

    self.update_attribute(:student_no, "#{Date.today.year}#{order_of_enrollment.to_s.rjust(6, '0')}")
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
   @user_subjects = current_user.student.subjects.all
   @block = current_user.student.blocks.first
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:block_ids)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(student) do |f| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :blocks %>
    <%= f.collection_select(:block_ids, Block.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<div class="card-columns">
  <% @user_subjects.each do |user_subject| %>
   <%= link_to subject_assignment_path(id: @block.find_subject_assignment_id(user_subject)) do %>
      <div class="card">
        <div class="card-body">
          <h4 class="card-title"><%= user_subject.name %></h4>
          <h6 class="card-subtitle mb-2 text-muted">
            <%= user_subject.code %>
          </h6>
          <p class="card-text">
            <%= user_subject.search_teacher(current_user.student.blocks.first) %>
          </p>
        </div>
        <div class="card-footer">
          <small class="text-muted"> Final Grade: - </small>
        </div>
      </div>
    <% end %>
  <% end %>
</div> 

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>