config/routes.rb
Rails.application.routes.draw do
  default_url_options host: "localhost:3000"
 #devise_for :admin_users, {class_name: 'User' }.merge(ActiveAdmin::Devise.config)
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registrations: "registrations" }

  get ":student_no/:block", to: "students#index", param: :block, via: [:get], as: :block

  resources :students, path: '/:block', except: :index do
    collection do
      resources :subject_assignments do
        resources :announcements
        resources :exam_schedules
        resources :subject_grades
      end

    end
  end

  resources :teachers


  get "/teaching_loads", to: "teachers#index" do
  end
  
  devise_scope :user do
    root 'devise/sessions#new'
  end
  
end

app/models/subject_assignment.rb
class SubjectAssignment < ApplicationRecord
  belongs_to :subject
  belongs_to :block
  belongs_to :teacher, optional: true
  has_many :announcements
  has_many :lectures
  has_many :exam_schedules

  def teaching_load_name
    "#{self.subject.name}@#{self.block.complete_block_name}"
  end

end

app/controllers/subject_assignments_controller.rb
class SubjectAssignmentsController < ApplicationController
  before_action :set_subject_assignment, only: [:show, :edit, :update, :destroy]

  # GET /subject_assignments
  # GET /subject_assignments.json
  def index
    @subject_assignments = SubjectAssignment.all
  end


  # GET /subject_assignments/1
  # GET /subject_assignments/1.json
  def show
    @subject_assignment = SubjectAssignmentFacade.new(@subject_assignment)
   #@subject = @subject_assignment.subject
   #@teacher = @subject_assignment.teacher
   #@announcements = @subject_assignment.announcements.order(updated_at: :desc)
   #@announcement = @subject_assignment.announcements.new
   #@exam_schedules = @subject_assignment.exam_schedules.order(updated_at: :desc)
   #@exam_schedule = @subject_assignment.exam_schedules.new
  end

  # GET /subject_assignments/new
  def new
    @subject_assignment = SubjectAssignment.new
  end

  # GET /subject_assignments/1/edit
  def edit
  end

  # POST /subject_assignments
  # POST /subject_assignments.json
  def create
    @subject_assignment = SubjectAssignment.new(subject_assignment_params)

    respond_to do |format|
      if @subject_assignment.save
        format.html { redirect_to @subject_assignment, notice: 'Subject assignment was successfully created.' }
        format.json { render :show, status: :created, location: @subject_assignment }
      else
        format.html { render :new }
        format.json { render json: @subject_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subject_assignments/1
  # PATCH/PUT /subject_assignments/1.json
  def update
    respond_to do |format|
      if @subject_assignment.update(subject_assignment_params)
        format.html { redirect_to @subject_assignment, notice: 'Subject assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject_assignment }
      else
        format.html { render :edit }
        format.json { render json: @subject_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subject_assignments/1
  # DELETE /subject_assignments/1.json
  def destroy
    @subject_assignment.destroy
    respond_to do |format|
      format.html { redirect_to subject_assignments_url, notice: 'Subject assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject_assignment
      @subject_assignment = SubjectAssignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_assignment_params
      params.fetch(:subject_assignment, {})
    end
end

app/helpers/subject_assignments_helper.rb
module SubjectAssignmentsHelper
end

app/views/subject_assignments/_announcement_form.html.erb
<%= form_for announcement, 
  url: subject_assignment_announcements_path(subject_assignment_id: @subject_assignment.id) do |f| %>
  <!--Modal function start-->  
  <div class="modal fade" id="add_announcement" tabindex="-1", data-backdrop="false">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-body">
              <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: "form-control", autofocus: true %>
              </div>

              <div class="form-group">
                <%= f.label :content %>
                <%= f.text_area :content, class: "form-control" %>
              </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            Close
          </button>

          <%= f.submit class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
  <!--Modal Function End-->
<% end %>

app/views/subject_assignments/_bulletin_board.html.erb
<div class="card text-center" id="remove-border">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <%= link_to "Exam Schedule", "#exam_scheds", class: 'nav-link active', data: { toggle: 'tab' } %>
      </li>

      <li class="nav-item">
        <%= link_to "Announcements", "#announcements", class: 'nav-link', data: { toggle: "tab" } %>
      </li>

      <!-- Deadlines Navbar
      <li class="nav-item">
        <%= link_to "Deadlines", "#deadlines", class: 'nav-link', data: { toggle: "tab" } %>
      </li>
      -->

    </ul>
  </div>

  <!--Exam Schedule content-->
  <div class="tab-content">
    <div class="tab-pane fade show active" id="exam_scheds">
      <% if current_user.has_role? :teacher %>
        <%= link_to "javascript:;", data: { toggle: "modal", target: "#add_exam_sched" } do %>
          <div class="card mb-3">
              <div class="card-block">
                <h4 class="card-title">Add a new schedule</h4>
              </div>
          </div>
        <% end %>
      <% end %>

    <% @subject_assignment.exam_schedules.each do |exam_schedule| %>
      <div class="card mb-3 show-crud">
          <div class="card-block">
            <h4 class="card-title"><%= exam_schedule.title %></h4>
            <p class="card-text"><%= exam_schedule.details %></p>
          <% if current_user.has_role? :teacher %>
            <div class="crud-tools">
              <%#= link_to "Edit", edit_subject_assignment_exam_schedule_path(id: exam_schedule, subject_assignment_id: @subject_assignment), remote: true %>
              <%= link_to "Delete", subject_assignment_exam_schedule_path(id: exam_schedule, subject_assignment_id: @subject_assignment.id),
                method: :delete, 
                data: { confirm: 'Are you sure?' } %>
            </div>
          <% end %>
          </div>

          <div class="card-footer">
            <div class="row">
              <div class="col-md-6">
                <small>Exam Start: 
                  <%=format_date(exam_schedule.start_date) %>
                </small>
              </div>

              <div class="col-md-6">
                <small>Exam Finish: 
                  <%= format_date(exam_schedule.end_date) %>
                </small>
              </div>
            </div>
          </div>
      </div>
    <% end %>
    </div>

    <!--Announcement content-->
    <div class="tab-pane fade" id="announcements">
      
      <% if current_user.has_role? :teacher %>
        <a href="javascript:;" data-toggle="modal" data-target="#add_announcement">
          <div class="card mb-3">
            <div class="card-block">
              <h4 class="card-title">
                Add new announcement
              </h4>
            </div>
          </div>
        </a>
      <% end %> 

      <% @subject_assignment.announcements.each do |announcement| %>
        <div class="card mb-3 show-crud">
            <div class="card-block">
              <h4 class="card-title">
                <%= announcement.title %>
              </h4>
              <p class="card-text">
                <%= announcement.content %>
              </p>
          <% if current_user.has_role? :teacher %>
            <div class="crud-tools">
              <%#= link_to "Edit", edit_subject_assignment_exam_schedule_path(id: exam_schedule, subject_assignment_id: @subject_assignment), remote: true %>
              <%= link_to "Delete", subject_assignment_announcement_path(id: announcement, subject_assignment_id: @subject_assignment.id),
                method: :delete, 
                data: { confirm: 'Are you sure?' } %>
            </div>
          <% end %>
            </div>
        </div>
      <% end %>
    </div>
    <!--End of Announcement-->

    <!--Deadlines
    <div class="tab-pane fade" id="deadlines">
      <div class="card mb-3">
          <div class="card-block">
            <h4 class="card-title">Deadline1</h4>
            <p class="card-text">Some content</p>
          </div>
      </div>
      <div class="card mb-3">
          <div class="card-block">
            <h4 class="card-title">Deadline2</h4>
            <p class="card-text">Some content</p>
          </div>
      </div>
    </div> -->
    <!--End of deadlines-->

  </div>

  
</div>

<%= render 'announcement_form', announcement: @subject_assignment.announcement %>
<%= render 'exam_sched_form', exam_schedule: @subject_assignment.exam_schedule %>

app/views/subject_assignments/_edit_exam_sched.html.erb
<%= form_for exam_sched , 
  url: subject_assignment_exam_schedules_path(subject_assignment_id: @subject_assignment) do |f| %>

  <div class="modal fade" id="add_exam_sched" tabindex="-1", data-backdrop="false">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-body">
              <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: "form-control", autofocus: true %>
              </div>

              <div class="form-group">
                <%= f.label :details %>
                <%= f.text_area :details, class: "form-control" %>
              </div>

              <div class="form-group">
                <%= f.label :start_date %><br />
                <%= f.datetime_local_field :start_date, value: Time.now.strftime("%Y-%m-%dT%H:%M:00") %>
              </div>

              <div class="form-group">
                <%= f.label :end_date %><br />
                <%= f.datetime_local_field :end_date, value: Time.now.strftime("%Y-%m-%dT%H:%M:00") %>
              </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            Close
          </button>

          <%= f.submit class: "btn btn-primary", id: "submit" %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/subject_assignments/_exam_sched_form.html.erb
<%= form_for exam_schedule , 
  url: subject_assignment_exam_schedules_path(subject_assignment_id: @subject_assignment.id) do |f| %>

  <div class="modal fade" id="add_exam_sched" tabindex="-1", data-backdrop="false">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-body">
              <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: "form-control", autofocus: true %>
              </div>

              <div class="form-group">
                <%= f.label :details %>
                <%= f.text_area :details, class: "form-control" %>
              </div>

              <div class="form-group">
                <%= f.label :start_date %><br />
                <%= f.datetime_local_field :start_date, value: Time.now.strftime("%Y-%m-%dT%H:%M:00") %>
              </div>

              <div class="form-group">
                <%= f.label :end_date %><br />
                <%= f.datetime_local_field :end_date, value: Time.now.strftime("%Y-%m-%dT%H:%M:00") %>
              </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            Close
          </button>

          <%= f.submit class: "btn btn-primary", id: "submit" %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/subject_assignments/_form.html.erb
<%= form_for(subject) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :code %>
  <%= f.text_field :code %>
  <%= f.submit "Create Subject" %>
<% end %>

app/views/subject_assignments/_side_bar.html.erb
<div>
  <ul class="nav flex-column">
    <li class="nav-item">
      <%= link_to "Lectures", "#", class: "nav-link" %>
      <%= link_to "Assignments", "#", class: "nav-link" %>
      <% if current_user.has_role? :student%>
        <%= link_to "My Grade Summary", "#", class: "nav-link" %>
      <% elsif current_user.has_role? :teacher%>
        <%= link_to "Grade Students", "#", class: "nav-link" %>
      <% end %>

    </li>
  </ul>
</div>

app/views/subject_assignments/edit.html.erb
<h1>Editing Subject Assignment</h1>

<%= render 'form', subject_assignment: @subject_assignment %>

<%= link_to 'Show', @subject_assignment %> |
<%= link_to 'Back', subject_assignments_path %>

app/views/subject_assignments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subject Assignments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subject_assignments.each do |subject_assignment| %>
      <tr>
        <td><%= link_to 'Show', subject_assignment %></td>
        <td><%= link_to 'Edit', edit_subject_assignment_path(subject_assignment) %></td>
        <td><%= link_to 'Destroy', subject_assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject Assignment', new_subject_assignment_path %>

app/views/subject_assignments/new.html.erb
<h1>Add a new subject</h1>
<%= render 'form', subject: @subject %>
<%= link_to 'Logout', destroy_user_session_path, method: :delete %>

app/views/subject_assignments/show.html.erb
<div class="row">
  <div class="col-md-2">
    <div>
      <%= image_tag @subject_assignment.teacher_image %>
      <p><%= @subject_assignment.subject_name %></p>
      <p><%= @subject_assignment.subject_code %></p>
      <p><%= @subject_assignment.teacher_name %></p>
    </div>
    <%#= render "side_bar" %>
  </div>

  <div class="col-md-8">
    <%= render "bulletin_board" %>
    
  </div>
</div>